platform :ios, '9.0'

plugin 'cocoapods-binary'

inhibit_all_warnings!
keep_source_code_for_prebuilt_frameworks!
#all_binary!
#disabled_prebuild_local_pod

target 'demo' do
  use_frameworks!

  pod 'FFLog', :binary => true
  pod 'Lokal', :path => 'Lokal', :binary => true

end
