platform :ios, '9.0'
plugin 'cocoapods-binary'

use_frameworks!
all_binary!


target 'demo' do

  pod 'FFLog', :binary => true
  pod 'Lokal', :path => 'Lokal', :binary => true
  
#  pod 'FFLog'
#  pod 'Lokal', :path => 'Lokal'

end
